from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response

from ..dependencies import require_api_key
from ..services import media_cache

router = APIRouter(prefix="/api/v1", tags=["stickers"], dependencies=[Depends(require_api_key)])


@router.get("/stickers/{sticker_id}")
def get_sticker(sticker_id: str) -> Response:
    """Serves a sticker generated by !sticker. Short-lived: bots must fetch it right after the reply."""
    cached = media_cache.get(sticker_id)
    if cached is None:
        raise HTTPException(status_code=404, detail="Sticker not found or expired")
    data, mimetype = cached
    return Response(content=data, media_type=mimetype)
